// ESLint config — see https://docs.expo.dev/guides/using-eslint/
//
// Scope note: this lints the *app* only. Two surfaces are deliberately out:
//   • `supabase/functions/**` is Deno, with https:// and npm: imports that the
//     Node resolver can't see. It's checked by `deno check` instead — see the
//     `verify-changes` skill.
//   • `.expo/**` is generated by expo-router (typed routes) and isn't ours.
const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');

module.exports = defineConfig([
  {
    ignores: [
      'dist/*',
      'web-build/*',
      '.expo/**',
      'supabase/functions/**',
      // Git worktrees created inside the repo (Claude Code's EnterWorktree)
      // are separate checkouts — linting them double-reports every finding.
      '.claude/worktrees/**',
      'web/**',
      'scripts/**',
    ],
  },
  expoConfig,
  {
    // Scoped to TS: `@typescript-eslint` is only registered for these files by
    // expoConfig, and a rule referencing an out-of-scope plugin is a hard
    // config error rather than a skipped rule.
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      // The house convention for a deliberately-ignored error is a leading
      // underscore (`catch (_err)`), used in ~20 places. Honour it rather
      // than rewriting every call site to satisfy the default pattern.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      // `useRef(new Animated.Value(0)).current` is the standard RN Animated
      // idiom (the value object is stable and mutated by the driver, never
      // read for rendering). The rule can't distinguish it from a genuine
      // read-ref-during-render bug, so it's a warning here: worth a look in
      // review, not a build break.
      'react-hooks/refs': 'warn',
      // Several screens intentionally reset state when the signed-in user
      // changes, so one account never shows another's data. That's a correct
      // use of set-state-in-effect; the rule flags the shape regardless.
      'react-hooks/set-state-in-effect': 'warn',
      // Assigning to a Reanimated shared value's `.value` is that library's
      // documented API, not a mutation of React state. Same story as the two
      // rules above: a React-Compiler-era rule that can't see the difference.
      'react-hooks/immutability': 'warn',
    },
  },
]);
